app:
  url: http://localhost:8080

spring:

  config:
    import: classpath:application.secrets.yml

  # DB Properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: db/changelog/main-changelog.xml

  # Email Configuration
  mail:
    host: smtp.yandex.by
    port: 465
    username: evolve.socialnetwork@yandex.by
    password: ${mail.password}
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  # Docker Configuration
  docker:
    compose:
      file: compose.yaml
      skip:
        in-tests: false

# Authentication
token:
  timeout:
    access: 3600
    refresh: 7200
  signing:
    key: ${jwt.signature}

# Logging
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
    web: debug

mail:
  debug: true
